[package]
name = "ocl"
version = "0.1.0"
authors = ["Dr. David Alan Gilbert <dave@treblig.org>"]

[dependencies]
glib-sys = { version = "0.5.0" }
gdk-sys = { version = "0.5.0" }
cairo-rs = { version = "0.3.0", features = ["png"] }
gtk = { version = "0.3.0", features = ["v3_16"] }
ocl = { version = "0.18" }
nalgebra = { version = "0.13" }
bincode = { version = "0.9.2" }
